import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'

export default function Home() {

  let [todos, setTodos] = useState([]);

  const clickTodo = event => {
    let doneClassName = "hover:cursor-pointer line-through text-gray-600";
    if (event.target.className == doneClassName) {
      event.target.className = "hover:cursor-pointer";
    } else {
      event.target.className = doneClassName;
    }
  }

  const handleKeyDown = event => {
    if (event.key === 'Enter') {
      const newTodo = {
        "id": todos.length+1,
        "task": event.target.value,
      }
      setTodos([...todos, newTodo])
      event.target.value = ""
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div className='flex flex-col gap-4'>
          <div>
            <h1 className={styles.title}>todo</h1>
          </div>

          {todos.map(todo => (
            <div key={todo.id}>
              <label onClick={clickTodo} className="hover:cursor-pointer">{todo.task}</label>
          </div>
          ))}
          <div>
              <input
                type="text"
                className="bg-transparent border-b-2 focus:outline-none"
                onKeyDown={handleKeyDown}
              />
          </div>
        </div>

      </main>
    </div>
  )
}
