import Head from 'next/head'
import styles from '../styles/Home.module.css'

function strikethrough(event) {
  console.log(event);
  let doneClassName = "ml-2 hover:cursor-pointer line-through text-gray-600";
  if (event.target.className == doneClassName) {
    event.target.className = "ml-2 hover:cursor-pointer";
  } else {
    event.target.className = doneClassName;
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div className='flex flex-col gap-4'>
          <div>
            <h1 className={styles.title}>todo</h1>
          </div>

          <div>
              <label onClick={strikethrough} className="ml-2 hover:cursor-pointer">Default checkbox</label>
          </div>
          <div>
              <label className="ml-2 line-through">Default checkbox</label>
          </div>
          <div>
              <input type="text" className="bg-transparent border-b-2 focus:outline-none"></input>
          </div>
        </div>

      </main>
    </div>
  )
}
